export default {
  dropdown_container: {
    border: "1px solid #dfe1e2",
    backgroundColor: "#fff",
    borderRadius: "12px",
    padding: "12px",
  },
  container: {
    display: "flex",
    gap: "12px",
  },
  remove_folder_container: {
    border: "2px solid #a3a8ae",
    borderRadius: "6px",
    width: "100%",
    display: "flex",
    flexDirection: "column" as "column",
    alignItems: "center",
    gap: "4px",
    padding: "46px 0",
  },
  remove_folder_description: {
    width: "180px",
    color: "#48515d",
    fontWeight: "400",
    fontSize: "12px",
    textAlign: "center" as "center",
  },
  remove_folder_icon: {
    width: "32px",
    height: "32px",
  },
  dropdown_button: {
    cursor: "pointer",
    position: "relative" as "relative",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    border: "none",
    backgroundColor: "transparent",
    padding: "4px 0",
  },
  arrow_up: {
    position: "absolute" as "absolute",
    right: "0",
    top: "50%",
    transform: "translateY(-50%)",
    width: "24px",
    height: "auto",
  },
  arrow_down: {
    position: "absolute" as "absolute",
    right: "0",
    top: "50%",
    transform: "translateY(-50%) rotate(180deg)",
    width: "24px",
    height: "auto",
  },
  radio_img: {
    width: "24px",
    height: "auto",
    marginRight: "12px",
  },
  button_name: {
    fontWeight: "500",
    fontSize: "14px",
  },
};
