export default {
  drop_page: {
    width: "100%",
    height: "100%",
    backgroundColor: "#f8fcfd",
    display: "flex",
    gap: "15px",
    padding: "12px 16px 16px",
  },
  drop_container: {
    flex: "1",
    padding: "16px 0 16px 16px",
    display: "flex",
    flexDirection: "column" as "column",
    backgroundColor: "#fff",
    borderRadius: "24px",
    overflow: "auto",
  },
  drop_container_title: {
    fontWeight: "700",
    lineHeight: "24px",
    fontSize: "18px",
    marginBottom: "12px",
  },
  side_section: {
    width: "252px",
    display: "flex",
    flexDirection: "column" as "column",
    alignItems: "center",
    justifyContent: "space-between",
  },
  drone_image: {
    width: "268px",
    height: "auto",
  },
  note_wrapper: {
    padding: "16px",
    backgroundColor: "#fff",
    borderRadius: "12px",
  },
  warning_title: {
    fontSize: "14px",
  },
  warning_subtitle: {
    textAlign: "center" as "center",
    fontSize: "12px",
    fontWeight: "400",
    color: "#48515d",
  },
  warning_example: {
    textAlign: "center" as "center",
    fontSize: "12px",
    color: "#48515d",
  },
  check_folder_button: {
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    width: "154px",
    height: "36px",
    border: "none",
    background: "#55BBD2",
    borderRadius: "6px",
    color: "#fff",

    "&:disabled": {
      backgroundColor: "#d1d4d6",
      color: "#48515d",
      cursor: "not-allowed",
    },
  },
  check_button_icon: {
    width: "16px",
    height: "16px",
  },
  check_button_text: {
    fontWeight: "500",
    fontSize: "14px",
    lineHeight: "24px",
    color: "inherit",
  },
  drop_page_footer: {
    display: "flex",
    width: "calc(100% + 32px)",
    marginLeft: "-16px",
    marginBottom: "-4px",
    padding: "12px 32px 0",
    justifyContent: "flex-end",
    marginTop: "auto",
    borderTop: "1px solid #dfe1e2",
  },
  container: {
    gap: "12px",
    width: "100%",
    display: "flex",
    flexDirection: "column" as "column",
    overflow: "auto",
    paddingBottom: "12px",
    paddingRight: "16px",
  },
};
